baseURL = "https://twintails.art/"
languageCode = "en-us"

enableRobotsTXT = true

title = "Twintails Industries"
pluralizelisttitles = false

hasCJKLanguage = true
summarylength = 40

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true