baseURL = "https://twintails.art/"
languageCode = "en-us"

title = "Twintails Industries"
pluralizelisttitles = false

hasCJKLanguage = true
summarylength = 40

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true