baseURL = "https://twintails.art/"
languageCode = "en-us"

title = "twintails.art"
pluralizelisttitles = false

hasCJKLanguage = true
summarylength = 40

[caches]
    [caches.images]
        dir    = ':cacheDir/:project'
        maxAge = "800h"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true